### ISSUE TITLE
add fallback for uncached pages when browsed offline with pwa

### ISSUE THREAD

**Issue by sigmaSd** [djibe/recommandations-medicales#10]
Its awesome that the pwa allows to browse the app offline for pages that were visited already.

But if you visit a page that was not cached , the user  gets an unfriendly screen:
![image](https://github.com/djibe/recommandations-medicales/assets/22427111/1a6ebceb-23d8-488b-8e6e-4fc41e2c6df9)

I suggest adding a user friendly fallback that tells the user that hes offline , so he can continue browsing cached parts of the site or decide to activate the network

**Comment by sigmaSd** [comment]
I couldn't figure where sw.js inside the public folder is coming from, anyway this feature should be simple to add if you can customize that file, you can just add an offline page fallback when fetch fails and the cache misses, here is an example https://discourse.gohugo.io/t/offline-fallback-hugo-pwa/

**Comment by sigmaSd** [comment]
I see now its generated from layout/index.js, so I guess the changes needs to go there

**Comment by djibe** [comment]
Hi. I created the page and updated the sw.js from https://github.com/wildhaber/offline-first-sw

But my /offline/ page doesn't show up.
Any idea @sigmaSd ?

**Comment by sigmaSd** [comment]
Hello, I'm not familiar with it, it seems to be more complex then I'm used to for sw,  I can try to debug it when I have time

**Comment by djibe** [comment]
That's very kind. Thank you

**Comment by sigmaSd** [comment]
I think it'd easier to add the offline page to your original sw code, if that sounds good I can do that , if not I'll try to debug the new code

**Comment by sigmaSd** [comment]
I tried for example this code for the sw and it works 
```js
const cacheName = "v5";
const offlinePage = "/offline/";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(cacheName).then((cache) => {
      return cache.add(offlinePage);
    }),
  );
});

self.addEventListener("fetch", (event) => {
  event.respondWith(
    (async () => {
      try {
        const a = await fetch(event.request);
        console.log("a", a);
        return a;
      } catch {
        // If no cache is available, respond with the offline page
        const hit = await caches.match(event.request);
        if (hit) return hit;
        return await caches.match(offlinePage);
      }
    })(),
  );
});
```

**Comment by sigmaSd** [comment]
This diff makes the offline page on the new code, but there are many warnings/errors in the console

```diff
diff --git a/layouts/index.js b/layouts/index.js
index 44f2ce69..ea670a10 100644
--- a/layouts/index.js
+++ b/layouts/index.js
@@ -1,23 +1,23 @@
 const CACHE_VERSION = 1;
 
-const BASE_CACHE_FILES = [
-    '/style.css',
-    '/search.json',
-    '/manifest.json',
-    '/favicon.png',
-];
+// const BASE_CACHE_FILES = [
+//     '/style.css',
+//     '/search.json',
+//     '/manifest.json',
+//     '/favicon.png',
+// ];
 
 const OFFLINE_CACHE_FILES = [
-    '/style.css',
-    '/offline/index.html',
+    // '/style.css',
+    '/offline/',
 ];
 
 const NOT_FOUND_CACHE_FILES = [
-    '/style.css',
+    // '/style.css',
     '/404.html',
 ];
 
-const OFFLINE_PAGE = '/offline/index.html';
+const OFFLINE_PAGE = '/offline/';
 const NOT_FOUND_PAGE = '/404.html';
 
 const CACHE_VERSIONS = {
@@ -94,7 +94,7 @@ function installServiceWorker() {
             caches.open(CACHE_VERSIONS.assets)
                 .then(
                     (cache) => {
-                        return cache.addAll(BASE_CACHE_FILES);
+                        // return cache.addAll(BASE_CACHE_FILES);
                     }
                 ),
             caches.open(CACHE_VERSIONS.offline)
```

**Comment by djibe** [comment]
It is really nice ! Thx
Works without `return cache.addAll(BASE_CACHE_FILES);` (and clearing the required files)

**Comment by djibe** [comment]
Hi @sigmaSd , I see many people reaching the /offline/ page.
Do you experience any trouble ? Or maybe it is the caching by the PWA ?

**Comment by sigmaSd** [comment]
Hello @djibe , I don't see any trouble it seems to work normally for me

Maybe it's caching of the offline page indeed

**Comment by djibe** [comment]
Thanks for your feedback @sigmaSd
