### ISSUE TITLE
Site du CNGOF

### ISSUE THREAD

**Issue by Its-Just-Nans** [djibe/recommandations-medicales#15]
Le site du CNGOF n'est plus en .net (https://cngof.net/) mais en .fr (https://cngof.fr/)

Je pense qu'a l'avenir il faudrait peut-être mettre des liens webarchives (en utilisant https://web.archive.org/save)

Fix : Voir PR #14

P.S: votre projet est super !!

**Comment by djibe** [comment]
Merci beaucoup pour les signalements.
Le contenu des Collèges évolue très vite, je dois me référer aux dernières publications uniquement.

Pour la PR, je vais la prendre en manuel pour éviter un rebuild complet du site.

Merci encore. Vous connaissez bien la santé ?

**Comment by Its-Just-Nans** [comment]
> Vous connaissez bien la santé ?

Malheureusement non - ce qui ajoute au fait que je trouve le projet très intéressant
