### ISSUE TITLE
use standalone or fullscreen for pwa display

### ISSUE THREAD

**Issue by sigmaSd** [djibe/recommandations-medicales#7]
Hello, thanks for this awesome project

I think the pwa would look better if it uses standalone or fullscreen as display , currently it uses minimal-ui which makes it have a top bar in chrome which breaks the feeling of a standalone app (comparison here https://superpwa.com/docs/article/web-app-manifest-display-modes-what-is-the-difference/)

It actually used to be the case, but it was changed at one point https://github.com/djibe/recommandations-medicales/commit/0ee684a8787f2b24b98d5a357c21180d4fb1b8e5#diff-a38e218cd3a281ca8908a1475a21609d48fb8bd7f3a35d34bca85c399e9dd003R26

Obviously if this is intended, its ok as well

**Comment by djibe** [comment]
Good idea !
thx.
Fixed.

**Comment by sigmaSd** [comment]
Thanks again, but I don't see new changes, is this change not pushed yet ?

**Comment by djibe** [comment]
Not yet :)
