### ISSUE TITLE
add a share button on pages

### ISSUE THREAD

**Issue by sigmaSd** [djibe/recommandations-medicales#8]
I like the pwa feeling wit standalone mode, but I think one thing can be improved, I wanted to share the current document I'm reading but there doesn't seem an obvious way to do it from inside the pwa app,

I think adding a share button is a good idea

**Comment by sigmaSd** [comment]
It can be just a simple link to the current document or use https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API

**Comment by djibe** [comment]
Hi, what sharing capabilities do you need ?

**Comment by sigmaSd** [comment]
Hello, just sharing the link to the current document, because as far as I can tell there is no obvious way to do it from inside the pwa app

**Comment by djibe** [comment]
Done :D

**Comment by djibe** [comment]
Oooops. Forgot to activate it on Mobile :D

**Comment by djibe** [comment]
Done

**Comment by sigmaSd** [comment]
awesome thanks
